// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCD66X2ZZG5eoXqt_47D5JzQ76vf5ihyw',
    appId: '1:402209232993:web:adc4331c7b383326b07220',
    messagingSenderId: '402209232993',
    projectId: 'hadomi-inan-93b51',
    authDomain: 'hadomi-inan-93b51.firebaseapp.com',
    storageBucket: 'hadomi-inan-93b51.firebasestorage.app',
    measurementId: 'G-QVTM5NPJVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUSP7AUGb_k_OU8qNzEQ31dn-9LhQsWg',
    appId: '1:402209232993:android:44f73dcbb2cd730db07220',
    messagingSenderId: '402209232993',
    projectId: 'hadomi-inan-93b51',
    storageBucket: 'hadomi-inan-93b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBauK-9KNcoYB-VtkQesT3lJA7Yl17KR00',
    appId: '1:402209232993:ios:65dcd83728ed8b3fb07220',
    messagingSenderId: '402209232993',
    projectId: 'hadomi-inan-93b51',
    storageBucket: 'hadomi-inan-93b51.firebasestorage.app',
    iosBundleId: 'com.example.hadomiInan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBauK-9KNcoYB-VtkQesT3lJA7Yl17KR00',
    appId: '1:402209232993:ios:65dcd83728ed8b3fb07220',
    messagingSenderId: '402209232993',
    projectId: 'hadomi-inan-93b51',
    storageBucket: 'hadomi-inan-93b51.firebasestorage.app',
    iosBundleId: 'com.example.hadomiInan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCD66X2ZZG5eoXqt_47D5JzQ76vf5ihyw',
    appId: '1:402209232993:web:9b044df755f3926eb07220',
    messagingSenderId: '402209232993',
    projectId: 'hadomi-inan-93b51',
    authDomain: 'hadomi-inan-93b51.firebaseapp.com',
    storageBucket: 'hadomi-inan-93b51.firebasestorage.app',
    measurementId: 'G-NS56T4BDDR',
  );

}